version: "3"

services:
  powerschool-technical-test-backend-development:
    container_name: powerschool-technical-test-backend-development
    restart: always
    build:
      context: ./backend/docker/development
      dockerfile: Dockerfile
      target: development
    command: sh -c "yarn install --no-cache --ignore-platform && yarn start:dev"
    ports:
      - 3000:3000
    networks:
      - powerschool-network-development
    volumes:
      - ./backend/:/usr/src/app

  powerschool-technical-test-frontend-development:
    container_name: powerschool-technical-test-frontend-development
    restart: always
    build:
      context: ./frontend/docker/development
      dockerfile: Dockerfile
      target: development
    command: sh -c "yarn install --no-cache --ignore-platform && yarn dev"
    ports:
      - 3001:3000
    networks:
      - powerschool-network-development
    volumes:
      - ./frontend/:/usr/src/app

networks:
  powerschool-network-development:
    driver: bridge
