version: "3"

services:
  powerschool-technical-test-backend:
    container_name: powerschool-technical-test-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/docker
      target: development
    command: sh -c "yarn install --no-cache --ignore-platform && yarn start:dev"
    ports:
      - 3000:3000
    networks:
      - powerschool-network
    volumes:
      - ./backend/:/usr/src/app

networks:
  powerschool-network:
    driver: bridge
