version: "3"

services:
  powerschool-technical-test-backend-production:
    container_name: powerschool-technical-test-backend-production
    restart: always
    build:
      dockerfile: ./docker/production/Dockerfile
      context: ./backend/
      target: production
    ports:
      - 8080:3000
    networks:
      - powerschool-network-production

  powerschool-technical-test-frontend-production:
    container_name: powerschool-technical-test-frontend-production
    restart: always
    build:
      dockerfile: ./docker/production/Dockerfile
      context: ./frontend/
      target: production
    ports:
      - 80:3000
    networks:
      - powerschool-network-production

networks:
  powerschool-network-production:
    driver: bridge
