version: "3"

services:
  powerschool-technical-test-backend:
    container_name: powerschool-technical-test-backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/docker/development
      target: development
    command: sh -c "yarn install --no-cache --ignore-platform && yarn start:dev"
    ports:
      - 3000:3000
    networks:
      - powerschool-network
    volumes:
      - ./backend/:/usr/src/app

  powerschool-technical-test-frontend:
    container_name: powerschool-technical-test-frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend/docker/development
      target: development
    command: sh -c "yarn install --no-cache --ignore-platform && yarn dev"
    ports:
      - 3001:3000
    networks:
      - powerschool-network
    volumes:
      - ./frontend/:/usr/src/app

networks:
  powerschool-network:
    driver: bridge
