version: "3"

services:
  powerschool-technical-test-backend-production:
    container_name: powerschool-technical-test-backend-production
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/docker/production
      target: production
    ports:
      - 3000:3000
    networks:
      - powerschool-network-production

  powerschool-technical-test-frontend-production:
    container_name: powerschool-technical-test-frontend-production
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend/docker/production
      target: production
    ports:
      - 3001:3000
    networks:
      - powerschool-network-production

networks:
  powerschool-network-production:
    driver: bridge
